version: '3'

services:
    hugapi_workspace:
        image: tonykingnz/hugapi-workspace:3.8.6-buster
        volumes:
            - ./:/root
              #- ./hugapi_workspace:root #dont work two at same place  
        ports:
            - 8000:8000
        depends_on:
            - acme-db-postgres
#        tty: true

    acme-db-postgres:
        image: 'postgres:alpine'
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=acme-db

#   hugapi_server:
#        image: tonykingnz/hugapi-server:3.8.5buster
#        volumes:
#            - ./hugapi_app:/root
#        ports:
#            - 8080:8080 ???
#        depends_on:
#            - acme-db-postgres
#        tty: true

    
#    gunicorn:
#        build: ./gunicorn
#        volumes:
#            - hugapi_app
#        ports:
#            - "8000:8000"
#              #        links:
#              #         - hugapi
